version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: all
  disable:
    - wsl
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - lll
    - varnamelen
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: 75
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - maintidx
        path: _test\.go
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
