run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - nolintlint
    - depguard
    - gci
    - ireturn
    - paralleltest
    - tparallel
    - varnamelen
    - tenv
    - gofumpt
    - goimports
issues:
  exclude-dirs:
    - tmp
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
linters-settings:
